apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/Varshaja-31/flux-repo.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  validation: client
