apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-sync
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  validation: client
